import { NextApiRequest, NextApiResponse } from "next";

const posts = [
  {
    id: 1,
    title: "아유 하기 싫어 ㅠㅠ",
    content: "아유 일 하기 싫어 싫어 너무 싫어!",
    writer: "박명수",
    view: 93,
    comments: 99,
    likes: 67,
    createTime: "2022/10/09",
    image: "post_image_01",
  },
  {
    id: 2,
    title: "Now and Then",
    content:
      "montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl",
    writer: "Helge Sellack",
    view: 38,
    comments: 75,
    likes: 78,
    createTime: "2023/04/29",
  },
  {
    id: 3,
    title: "Risky Business",
    content:
      "interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien",
    writer: "Emmery Theobalds",
    view: 73,
    comments: 20,
    likes: 5,
    createTime: "2022/09/05",
  },
  {
    id: 4,
    title: "Talking About Sex",
    content:
      "justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper",
    writer: "Alic Seagrove",
    view: 85,
    comments: 26,
    likes: 6,
    createTime: "2023/06/03",
  },
  {
    id: 5,
    title: "Johnny Mnemonic",
    content: "praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus",
    writer: "Alair Pering",
    view: 91,
    comments: 23,
    likes: 38,
    createTime: "2022/09/25",
  },
  {
    id: 6,
    title: "Interkosmos",
    content:
      "eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",
    writer: "Dav Peterken",
    view: 24,
    comments: 16,
    likes: 17,
    createTime: "2022/10/31",
  },
  {
    id: 7,
    title: "Sound of Thunder, A",
    content: "id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien",
    writer: "Merle Weems",
    view: 28,
    comments: 50,
    likes: 15,
    createTime: "2023/03/11",
  },
  {
    id: 8,
    title: "Born on the Fourth of July",
    content:
      "maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin",
    writer: "Norene Pettet",
    view: 43,
    comments: 18,
    likes: 87,
    createTime: "2022/09/07",
  },
  {
    id: 9,
    title: "Dangerous",
    content: "in hac habitasse platea dictumst etiam faucibus cursus urna ut",
    writer: "Lynett Rushby",
    view: 66,
    comments: 95,
    likes: 52,
    createTime: "2022/11/06",
  },
  {
    id: 10,
    title: "African Cats",
    content: "mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus",
    writer: "Finley Lawee",
    view: 80,
    comments: 3,
    likes: 17,
    createTime: "2023/01/17",
  },
  {
    id: 11,
    title: "Twilight of a Woman's Soul (Sumerki zhenskoi dushi)",
    content: "lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in",
    writer: "Flor Cess",
    view: 91,
    comments: 58,
    likes: 11,
    createTime: "2023/03/24",
  },
  {
    id: 12,
    title: "Redemption: The Stan Tookie Williams Story",
    content: "orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti",
    writer: "Martyn Wyke",
    view: 35,
    comments: 5,
    likes: 85,
    createTime: "2022/09/09",
  },
  {
    id: 13,
    title: "Reclaim Your Brain (Free Rainer)",
    content:
      "luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat",
    writer: "Wendall Greenlees",
    view: 55,
    comments: 4,
    likes: 86,
    createTime: "2023/01/03",
  },
  {
    id: 14,
    title: "Our Lady of the Assassins (Virgen de los sicarios, La)",
    content:
      "risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis",
    writer: "Ansell Shoute",
    view: 15,
    comments: 67,
    likes: 89,
    createTime: "2023/01/01",
  },
  {
    id: 15,
    title: "Coward, The (Kapurush)",
    content:
      "mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt",
    writer: "Anderson Grattage",
    view: 75,
    comments: 53,
    likes: 94,
    createTime: "2023/04/18",
  },
  {
    id: 16,
    title: "Prefab People, The (Panelkapcsolat)",
    content:
      "mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue",
    writer: "Mady Lagen",
    view: 1,
    comments: 36,
    likes: 93,
    createTime: "2023/06/03",
  },
  {
    id: 17,
    title: "I Accuse",
    content: "justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in",
    writer: "Harris Farlow",
    view: 31,
    comments: 2,
    likes: 65,
    createTime: "2022/12/18",
  },
  {
    id: 18,
    title: "Back to School",
    content:
      "metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci",
    writer: "Ogden Teager",
    view: 95,
    comments: 91,
    likes: 85,
    createTime: "2023/01/18",
  },
  {
    id: 19,
    title: "At Middleton",
    content:
      "mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales",
    writer: "Doris MacConnulty",
    view: 29,
    comments: 29,
    likes: 44,
    createTime: "2023/01/16",
  },
  {
    id: 20,
    title: "Mr. Wu",
    content:
      "cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet",
    writer: "Nerissa Delort",
    view: 34,
    comments: 53,
    likes: 26,
    createTime: "2022/09/21",
  },
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  return res.status(200).json(posts);
}
