name: Docker
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          echo  "1"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          echo  "2"
          docker build -t ${{ secrets.DOCKER_REPO }}/yeh_front .
          
          echo  "3"
          docker push ${{ secrets.DOCKER_REPO }}/yeh_front

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull ${{ secrets.DOCKER_REPO }}/yeh_front
            docker-compose up -d
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
