name: Docker
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy: 
      matrix: 
        node-version: [16.14.x] 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ec2-user/yeh_front/
            git pull origin main
            rm -rf out
            npm install
            npm run build
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_REPO }}/yeh_front .
            docker push ${{ secrets.DOCKER_REPO }}/yeh_front
            docker pull ${{ secrets.DOCKER_REPO }}/yeh_front
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
